name: Auto Versioning

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2️⃣ Configura o Git para o commit automático
      - name: Set up Git
        run: |
          git config user.name "CI Bot"
          git config user.email "ci-bot@github.com"

      # 3️⃣ Incrementa a versão
      - name: Increment version number
        id: bump
        run: |
          VERSION_FILE="version.txt"
          CURRENT_VERSION=$(cat $VERSION_FILE)
          echo "Versão atual: $CURRENT_VERSION"

          VERSION_NUM=${CURRENT_VERSION#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NUM"
          PATCH=$((PATCH + 1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"

          echo "$NEW_VERSION" > $VERSION_FILE
          echo "Nova versão: $NEW_VERSION"

          # Exporta a nova versão como saída
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # 4️⃣ Faz commit do novo arquivo version.txt
      - name: Commit updated version
        run: |
          git add version.txt
          git commit -m "chore: atualiza versão para ${{ steps.bump.outputs.new_version }}" || echo "Nenhuma alteração a commitar"

      # 5️⃣ Envia as mudanças de volta à branch main
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

